# FSI Fraud Detection - Production Environment Configuration
# Unified pod deployment: Frontend + Fraud Backend + AML Backend
# Environment: Production

# Frontend main container environment variables
env:
  NODE_ENV: production
  PORT: '8080'
  HOSTNAME: '0.0.0.0'
  # Client-side API URLs (proxied through Next.js API routes)
  NEXT_PUBLIC_API_URL: /api/fraud
  NEXT_PUBLIC_AML_API_URL: /api/aml
  # Server-side backend URLs for proxy routes (internal pod communication)
  FRAUD_BACKEND_URL: http://localhost:8000
  AML_BACKEND_URL: http://localhost:8001
  # WebSocket proxy port
  WS_PROXY_PORT: '8081'

# Sidecar containers (both backends)
sidecarContainers:
  # Fraud Detection Backend (port 8000)
  - name: fraud-backend
    image: 795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/fsi-fraud-detection-backend-prod:prod-latest
    imagePullPolicy: Always # Always pull latest image to avoid stale cache
    ports:
      - containerPort: 8000
        name: fraud-api
    resources:
      requests:
        memory: '256Mi'
        cpu: '100m'
      limits:
        memory: '750Mi'
        cpu: '350m'
    env:
      - name: PORT
        value: '8000'
      - name: HOST
        value: '0.0.0.0'
      - name: PYTHONUNBUFFERED
        value: '1'
      # AWS Configuration (IRSA - no keys needed)
      - name: AWS_REGION
        value: 'us-east-1'
      - name: AWS_USE_SSO
        value: 'false'
      # MongoDB Configuration (from secrets)
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: MONGODB_URI
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: DB_NAME

  # AML/KYC Backend (port 8001)
  - name: aml-backend
    image: 795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/fsi-fraud-detection-aml-backend-prod:prod-latest
    imagePullPolicy: Always # Always pull latest image to avoid stale cache
    ports:
      - containerPort: 8001
        name: aml-api
    resources:
      requests:
        memory: '256Mi'
        cpu: '100m'
      limits:
        memory: '750Mi'
        cpu: '350m'
    env:
      - name: PORT
        value: '8001'
      - name: HOST
        value: '0.0.0.0'
      - name: PYTHONUNBUFFERED
        value: '1'
      # AWS Configuration (IRSA - no keys needed)
      - name: AWS_REGION
        value: 'us-east-1'
      - name: AWS_USE_SSO
        value: 'false'
      # MongoDB Configuration (from secrets)
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: AML_MONGODB_URI
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: AML_DB_NAME
      # Atlas Search Index Names (from secrets)
      - name: ATLAS_SEARCH_INDEX
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: ATLAS_SEARCH_INDEX
      - name: ATLAS_TEXT_SEARCH_INDEX
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: ATLAS_TEXT_SEARCH_INDEX
      - name: ENTITY_VECTOR_INDEX
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: ENTITY_VECTOR_INDEX
      - name: TRANSACTION_VECTOR_INDEX
        valueFrom:
          secretKeyRef:
            name: fsi-fraud-detection-secrets
            key: TRANSACTION_VECTOR_INDEX

# Service Account with IRSA for AWS Bedrock access
serviceAccount:
  enabled: true
  irsa:
    accountId: '275662791714'
    roleName: 'kanopy-prod-cicd-irsa'
