"""Shared MongoDB client configuration.

Single source of truth for the Atlas application name. Keep this here rather than
inline at each MongoClient/AsyncIOMotorClient call: connection strings copied from
the Atlas UI, and snippets generated by LLMs, routinely drop the appName option,
which silently breaks observability and content attribution for this demo.

Distinct from backend/db_config.py's value so Atlas can tell fraud-service traffic
apart from AML-service traffic, even though both share one cluster.

Naming convention: devrel-MEDIUM-PRIMARY-SECONDARY-OPTIONAL
"""

APP_NAME = "devrel-github-python-aml-kyc-langgraph"
